In [1]:
import numpy

In [2]:
A = numpy.array([10,20,30,40,50])

In [3]:
A

array([10, 20, 30, 40, 50])

In [4]:
A[0]

10

In [5]:
A[-1]

50

In [6]:
A[2] = 100

In [7]:
A

array([ 10,  20, 100,  40,  50])

In [8]:
for i in A:
    print(i)

10
20
100
40
50


In [9]:
A

array([ 10,  20, 100,  40,  50])

In [10]:
A[2:]

array([100,  40,  50])

In [1]:
import numpy as np

In [12]:
B = np.arange(10,20,4)
B

array([10, 14, 18])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# LINSPACE

In [15]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [19]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [20]:
np.linspace(0,6.28,50)

array([0.        , 0.12816327, 0.25632653, 0.3844898 , 0.51265306,
       0.64081633, 0.76897959, 0.89714286, 1.02530612, 1.15346939,
       1.28163265, 1.40979592, 1.53795918, 1.66612245, 1.79428571,
       1.92244898, 2.05061224, 2.17877551, 2.30693878, 2.43510204,
       2.56326531, 2.69142857, 2.81959184, 2.9477551 , 3.07591837,
       3.20408163, 3.3322449 , 3.46040816, 3.58857143, 3.71673469,
       3.84489796, 3.97306122, 4.10122449, 4.22938776, 4.35755102,
       4.48571429, 4.61387755, 4.74204082, 4.87020408, 4.99836735,
       5.12653061, 5.25469388, 5.38285714, 5.51102041, 5.63918367,
       5.76734694, 5.8955102 , 6.02367347, 6.15183673, 6.28      ])

In [2]:
A = np.array([10,20,30,40,50,60]) # vector 6
B = np.array([[10,20],[30,40],[50,60]]) # matrix 3,2

In [3]:
A.ndim

1

In [4]:
B.ndim

2

In [5]:
A.shape

(6,)

In [6]:
B.shape

(3, 2)

In [7]:
B = np.array([[10,20,1],[30,40],[50,60]])

<ipython-input-7-24b4802b7437>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  B = np.array([[10,20,1],[30,40],[50,60]])


In [8]:
B

array([list([10, 20, 1]), list([30, 40]), list([50, 60])], dtype=object)

In [9]:
B.ndim

1

In [10]:
B.shape

(3,)

In [11]:
A = np.array([10,20,30,40,50,60]) # vector 6
B = np.array([[10,20],[30,40],[50,60]]) # matrix 3,2

In [12]:
A

array([10, 20, 30, 40, 50, 60])

In [13]:
B

array([[10, 20],
       [30, 40],
       [50, 60]])

In [14]:
A[4]

50

In [15]:
B[2][0]

50

In [16]:
B[2]

array([50, 60])

In [17]:
A = np.array([10,20,30,40])
B = np.array([[10],[20],[30],[40]])
C = np.array([[10,20,30,40]])

In [18]:
A.shape

(4,)

In [19]:
B.shape

(4, 1)

In [20]:
C.shape

(1, 4)

In [21]:
A[2], B[2,0], C[0][2]

(30, 30, 30)

# Random Elements

In [28]:
np.random.randint(0,20,50)

array([ 5, 17,  7,  7, 16, 16, 13,  1, 13,  0,  3,  1,  4,  9,  3,  8,  9,
        3, 16,  6, 11,  9,  4, 18,  5,  9,  7,  0, 12, 17,  4,  1,  6,  5,
        5, 11, 17, 17,  2, 19, 17, 12, 11, 13,  8, 12, 19, 15, 18,  8])

In [33]:
np.random.randint(0,20,(5,2))

array([[ 5, 13],
       [ 0, 10],
       [ 1,  0],
       [15,  0],
       [18, 14]])

In [34]:
np.random.randint(19,25,(60,5))

array([[20, 24, 23, 23, 24],
       [22, 23, 22, 24, 23],
       [20, 20, 21, 21, 23],
       [20, 19, 21, 21, 20],
       [19, 24, 20, 20, 24],
       [19, 22, 20, 22, 24],
       [23, 24, 21, 19, 23],
       [22, 24, 21, 21, 22],
       [24, 24, 21, 19, 24],
       [22, 22, 24, 23, 24],
       [22, 23, 23, 20, 22],
       [22, 19, 23, 24, 19],
       [22, 20, 22, 19, 23],
       [23, 24, 24, 21, 23],
       [21, 20, 23, 23, 20],
       [19, 21, 19, 22, 19],
       [21, 19, 23, 24, 21],
       [22, 23, 22, 23, 22],
       [22, 21, 24, 20, 24],
       [23, 21, 22, 24, 20],
       [19, 22, 20, 19, 22],
       [19, 19, 19, 24, 23],
       [23, 21, 19, 20, 19],
       [20, 21, 23, 19, 24],
       [21, 19, 23, 22, 24],
       [22, 22, 23, 21, 23],
       [21, 21, 21, 22, 21],
       [19, 20, 23, 24, 22],
       [19, 24, 21, 22, 23],
       [22, 24, 22, 24, 21],
       [23, 22, 24, 22, 23],
       [23, 21, 23, 24, 23],
       [22, 21, 23, 21, 20],
       [21, 22, 23, 24, 20],
       [20, 19

In [36]:
X = np.random.rand(5,3)

In [37]:
np.round(X,2)

array([[1.  , 0.9 , 0.93],
       [0.07, 0.37, 0.84],
       [0.39, 0.33, 0.85],
       [0.11, 0.76, 0.64],
       [0.16, 0.88, 0.14]])

In [38]:
X

array([[0.99905719, 0.90208002, 0.92521109],
       [0.07295612, 0.37449679, 0.84108477],
       [0.38578876, 0.33334605, 0.8500093 ],
       [0.10961488, 0.75967946, 0.63742357],
       [0.16409961, 0.87954139, 0.14437349]])

In [40]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [42]:
np.twos((5,2))

AttributeError: module 'numpy' has no attribute 'twos'